---
- name: install dependencies
  include_role:
    name: install-dependencies

- name: clone SRIOV Network Device Plugin repository
  git:
    repo: "{{ sriov_net_dp_git_url }}"
    version: "{{ sriov_net_dp_git_ref }}"
    dest: "{{ sriov_net_dp_dir }}"
    force: yes
  when:
    - inventory_hostname == groups['kube-node'][0]
    - sriov_net_dp_build_image_locally

- name: build SRIOV Network Device Plugin image behind proxy
  make:
    target: image
    chdir: "{{ sriov_net_dp_dir }}"
    params:
      HTTP_PROXY: "{{ proxy_env.http_proxy }}"
      HTTPS_PROXY: "{{ proxy_env.https_proxy }}"
  when:
    - inventory_hostname == groups['kube-node'][0]
    - sriov_net_dp_build_image_locally
    - '"http_proxy" in proxy_env or "https_proxy" in proxy_env'

- name: build SRIOV Network Device Plugin image
  make:
    target: image
    chdir: "{{ sriov_net_dp_dir }}"
  when:
    - inventory_hostname == groups['kube-node'][0]
    - sriov_net_dp_build_image_locally
    - '"http_proxy" not in proxy_env and "https_proxy" not in proxy_env'

- name: tag SRIOV Network Device Plugin image
  command: docker tag nfvpe/sriov-device-plugin:latest {{ registry_local_address }}/sriov-device-plugin:{{ sriov_net_dp_git_ref }}
  when:
    - inventory_hostname == groups['kube-node'][0]
    - sriov_net_dp_build_image_locally

- name: push SRIOV Network Device Plugin image to local registry
  command: docker push {{ registry_local_address }}/sriov-device-plugin:{{ sriov_net_dp_git_ref }}
  when:
    - inventory_hostname == groups['kube-node'][0]
    - sriov_net_dp_build_image_locally

- name: create Helm charts directory if needed
  file:
    path: "/usr/src/charts"
    state: directory
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: copy SRIOV Network Device Plugin Helm chart to the master node
  copy:
    src: "{{ role_path }}/charts/sriov-net-dp"
    dest: "/usr/src/charts/"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: set values for SRIOV Network Device Plugin Helm chart values for locally built and stored image
  set_fact:
    sriov_net_dp_image: "{{ registry_local_address }}/sriov-device-plugin"
    sriov_net_dp_tag: "{{ sriov_net_dp_git_ref }}"
  when:
    - sriov_net_dp_build_image_locally
    - inventory_hostname == groups['kube-master'][0]

- name: populate SRIOV Network Device Plugin Helm chart values template and push to master node
  template:
    src: "helm_values.yml.j2"
    dest: "/usr/src/charts/sriov-net-dp-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install SRIOV Network Device Plugin helm chart
  command: helm upgrade --install sriov-net-dp -f /usr/src/charts/sriov-net-dp-values.yml /usr/src/charts/sriov-net-dp
  when:
    - inventory_hostname == groups['kube-master'][0]
