---
- name: install dependencies
  include_role:
    name: install-dependencies

- name: clone Intel Device Plugins repository
  git:
    repo: "{{ intel_dp_git_url }}"
    version: "{{ intel_dp_git_ref }}"
    dest: "{{ intel_dp_dir }}"
    force: yes
  when:
    - inventory_hostname == groups['kube-node'][0]

- name: create Helm charts directory if needed
  file:
    path: /usr/src/charts
    state: directory
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install Intel QAT Device Plugin
  import_tasks: qat_plugin.yml
  when: qat_dp_enabled

- name: install Intel GPU Device Plugin
  import_tasks: gpu_plugin.yml
  when: gpu_dp_enabled
